name: amd-surv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.5
  - pip=22.1.2
  - pandas=1.4.2
  - mscorefonts=0.0.1 
  - r-base
  - rpy2
  - r-timeROC
  - r-survival
  - pip:
    - jupyter==1.0.0
    - ipykernel==6.15.2
    - imageio==2.13.1
    - mypy==0.910
    - numpy==1.21.4
    - pillow==8.4.0
    - pyyaml==6.0
    - scikit-image==0.19.0
    - opencv-python==4.5.5.64
    - torch==2.0.1
    - torchvision==0.15.2
    - git+https://github.com/lmkoch/multi-level-split#egg=multi-level-split==0.0.1
    - tqdm==4.64.1
    - matplotlib==3.6.2
    - wandb==0.15.5
    - scikit-survival==0.19.0.post1
    - plotly==5.13.0
    - jupyter-black==0.3.4
    - grad-cam==1.3.9